[package]
name = "bulk_ldap"
version = "0.1.0"
edition = "2021"

[dependencies]
ldap3 = "0.10.5"
csv = "1.1.6"
serde_bytes = "0.11.7"
serde = "1"
serde_derive = "1"
celes = "2.4.0"
clap = { version = "4.0.29", features = ["derive"] }